### ISSUE TITLE
readonly module not found

### ISSUE THREAD

**Issue by ghost** [PCGen/pcgen-utilities#25]
readonly module not found with perl 5.38.2

**Comment by karianna** [comment]
what happens with Perl 6+

**Comment by ghost** [comment]
i have windows and ActiveStatePerl and the max version is perl 5, i dont know how update or where download perl 6, maybe in linux?

**Comment by karianna** [comment]
ChatGPT suggests:

To install the missing `Readonly` module for Perl on Windows using ActiveState, you can follow these steps:

### Using the PPM (Perl Package Manager):

1. **Open the Command Prompt**:
   - Press `Win + R`, type `cmd`, and press Enter.

2. **Open PPM**:
   - In the Command Prompt, type `ppm` and press Enter to start the Perl Package Manager.

3. **Search for the `Readonly` module**:
   - In PPM, type the following command to search for the `Readonly` module:
     ```
     search Readonly
     ```

4. **Install the `Readonly` module**:
   - If the module is found in the search results, you can install it by typing:
     ```
     install Readonly
     ```

### Using the CPAN shell:

1. **Open the Command Prompt**:
   - Press `Win + R`, type `cmd`, and press Enter.

2. **Open CPAN shell**:
   - In the Command Prompt, type the following command to open the CPAN shell:
     ```
     cpan
     ```

3. **Install the `Readonly` module**:
   - Once you are in the CPAN shell, type the following command to install the `Readonly` module:
     ```
     install Readonly
     ```

### Using the CPAN client directly:

1. **Open the Command Prompt**:
   - Press `Win + R`, type `cmd`, and press Enter.

2. **Install the `Readonly` module**:
   - In the Command Prompt, type the following command to directly install the `Readonly` module using CPAN:
     ```
     cpan Readonly
     ```

### Using ActiveState's Platform:

1. **Visit the ActiveState Platform**:
   - Go to [ActiveState Platform](https://platform.activestate.com/).

2. **Log in or Sign up**:
   - Log in to your account or sign up if you don't have one.

3. **Create a Project**:
   - Create a new project or open an existing one.

4. **Add the `Readonly` module**:
   - In your project, go to the **Dependencies** section.
   - Search for the `Readonly` module and add it to your project.

5. **Download and Install the State Tool**:
   - Follow the instructions to download and install the State Tool if you haven't already.
   - The State Tool will handle the installation of the dependencies defined in your project.

6. **Install the Project**:
   - Use the State Tool to install your project which includes the `Readonly` module:
     ```
     state activate --default <your-project-name>
     ```

By following these methods, you should be able to install the `Readonly` module for Perl on your Windows system using ActiveState. If you encounter any issues, make sure you have the necessary permissions and an active internet connection.

**Comment by ghost** [comment]
thanks a lot cpan work, ppm didnt find Readonly module
